# Generated by Django 5.2.5 on 2025-08-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0005_course_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
